/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IKV2CreateBody = t.iface([], {
  "data": t.iface([], {
  }),
  "options": t.opt(t.iface([], {
    "cas": t.opt("number"),
  })),
});

export const IKV2CreateResponse = t.iface([], {
  "data": t.iface([], {
    "created_time": "string",
    "deletion_time": "string",
    "destroyed": "boolean",
    "version": "number",
  }),
});

export const IKV2ReadResponse = t.iface([], {
  "data": t.iface([], {
    "data": t.iface([], {
    }),
    "metadata": t.opt(t.iface([], {
      "created_time": "string",
      "deletion_time": "string",
      "destroyed": "boolean",
      "version": "number",
    })),
  }),
});

export const IKV2ListResponse = t.iface([], {
  "data": t.iface([], {
    "keys": t.array("string"),
  }),
});

export const IKV2ReadMetadataResponse = t.iface([], {
  "data": t.iface([], {
    "created_time": "string",
    "current_version": "number",
    "max_versions": "number",
    "oldest_version": "number",
    "updated_time": "string",
    "versions": t.iface([], {
    }),
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  IKV2CreateBody,
  IKV2CreateResponse,
  IKV2ReadResponse,
  IKV2ListResponse,
  IKV2ReadMetadataResponse,
};
export default exportedTypeSuite;
